# This is document with teams key attributes

title = "Team registry"

[hleb-albau]
name = "Hleb Albau"
gitcoin = "0x00725d89a2a2fb3b21fd1035b579cbcde4a0991b"
payouts = "0x002b9c5b537a1b6004ed720f32cc808fd6210f26"
github = "hleb-albau"
telegram = "hleb_albau"
keybase = "hleb_albau"

[litvintech]
name = "Valery Litvin"
gitcoin = "0xf103D2db8024F4B885433ADAF72032Ac58304e03"
payouts = "0x00cFF8CF7Bff03A9A2a81c01920ffD8cFa7AE9D0"
github = "litvintech"
telegram = "litvintech"
keybase = "litvintech"
ipfs-node = "QmXkd1HZKCy5oTdCDPTiU8kzh3kz79AeLmchCQLXetAJvH"

[xhipster]
name = "Dima Starodubcev"
gitcoin = "0x7C4401aE98F12eF6de39aE24cf9fc51f80EBa16B"
payouts = "0x7C4401aE98F12eF6de39aE24cf9fc51f80EBa16B"
github = "xhipster"
telegram = "xhipster"
keybase = "21xhipster"

[asadovka]
name = "Siarhei Sadau"
gitcoin = "0x318a6c1d757bD1938CefAa681c4CbC5380B34c47"
payouts = "0x63e65bc441334b27d2178f81f2d701e4e58c158a"
github = "asadovka"
telegram = "asadovka"
keybase = "asadovka"

[pechalka]
name = "Andrew Luzhkovsky"
gitcoin = "0x5d01F31f6EdA95489cA1E3c6357A9627fA2983DE"
payouts = "0x5d01F31f6EdA95489cA1E3c6357A9627fA2983DE"
github = "Pechalka"
telegram = "LuzhkovskyAndrey"
keybase = "andrewluzkovsky"

[vstavetski]
name = "Valentin Stavetski"
gitcoin = "0x379a23083a58b2b89f4dd307ad55f732bb5a20ef"
payouts = "0x4585C7EAA2cB96d4b59e868929EfaBEeb8e65b07"
github = "vstavetski"
telegram = "vstavetski"
keybase = "vstavetski"

[savetheales]
name = "Ales Puchilo"
gitcoin = "0x00466845B9906578ac86cBA4C2Dda0F2c46461F6"
payouts = "0x00CA47db1BE92C1072e973fd8DC4A082f7d70214"
github = "SaveTheAles"
telegram = "AlesPuchilo"
keybase = "savetheales"

[olga584]
name = "Olga Bessonova"
gitcoin = "0x9d7d6E753F055E40d3767337300e722E934086c1"
payouts = "0x9d7d6E753F055E40d3767337300e722E934086c1"
github = "Olga584"
telegram = "OlgaBessonova"
keybase = "olgabessonova"

[arturalbov]
name = "Artur Albau"
gitcoin = "0x006A1FD66F89B0d7F57d52dCe7d5Bf57DB20279f"
payouts = "0x00d3C9033570b8ADEA9C18780325A45635C55805"
github = "arturalbov"
telegram = "arturalbov"
keybase = "arturalbov"
