version: 2

workflows:
  version: 2
  default_workflow:
    jobs:
      - update_doc:
          filters:
            branches:
              only: master


jobs:
  update_doc:
    working_directory: ~/workdir
    docker:
      - image: circleci/node:10.15.1-browsers
    steps:
      - checkout
      - run:
          name: Update Docs
          command: |
            git clone -q --depth 1 https://${DOCS_GITHUB_TOKEN}@github.com/cybercongress/congress.git
      - deploy:
          name: Update site from congress repo
          working_directory: ~/workdir/congress
          command: |
            cd site
            rm -rf public/
            make build
            git config user.email "cybercongress42@gmail.com"
            git config user.name "Cyber Admin"
            git add public
            git commit -m "Circle CI: Update Site [skip ci]"
            git push -q -f https://${DOCS_GITHUB_TOKEN}@github.com/cybercongress/congress.git master:gh-pages
