version: 2

workflows:
  version: 2
  default_workflow:
    jobs:
      - update_doc:
          filters:
            branches:
              only: master

jobs:
  update_doc:
    working_directory: ~/build
    docker:
      - image: felicianotech/docker-hugo:latest
    steps:
      - checkout
      - run:
          command: |
            cd site
            rm -rf public/
            make build
            cd public
            git init
            git config user.email "cybercongress42@gmail.com"
            git config user.name "Cyber Admin"
            git add .
            gh-pages -m "deployed $CIRCLE_SHA1 with mkdocs [skip ci]"
            rm -rf public/
