version: 2

workflows:
  version: 2
  default_workflow:
    jobs:
      - update_doc:
          filters:
            branches:
              only: master

jobs:
  update_doc:
    working_directory: ~/build
    docker:
      - image: circleci/node:10.15.1-browsers
    steps:
      - checkout
      - run:
          command: |
            cd site
            rm -rf public/
            make build
            cd public
            git init
            git config user.email "cybercongress42@gmail.com"
            git config user.name "Cyber Admin"
            git add .
            git commit -m "Deploy to gh-pages"
            git push -f -q https://${DOCS_GITHUB_TOKEN}@github.com/cybercongress/congress.git master:gh-pages
            cd ..
            rm -rf public/
