# Project information
site_name: 'сyber•Search docs'
site_description: 'Knowledge base of cyber•Search'
site_author: 'cyber•Search team'
edit_uri: https://github.com/cybercongress/congress/edit/master/knowledge/docs

# Repository
repo_name: 'congress'
repo_url: 'https://github.com/cybercongress/congress'


# Copyright
copyright: 'Copyright &copy; 2018 cyber•Search'


# Configuration
theme:
  name: null
  custom_dir: 'theme_extend/material'
  font: robo
  favicon: 'img/Logo_cat.svg'
  logo: 'img/Logo_cat.svg'
  language: 'en'
  palette:
    primary: 'green'
  feature:
    tabs: true

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/cybercongress'

extra_css:
  - 'stylesheets/extra.css'
  - https://unpkg.com/mermaid@7.1.0/dist/mermaid.css
  - 'stylesheets/progressbar.css'
extra_javascript:
  - https://unpkg.com/mermaid@7.1.0/dist/mermaid.min.js

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
