# Project information
site_name: 'сyber•Search docs'
site_description: 'Knowledge base of cyber•Search'
site_author: 'cyber•Search team'
edit_uri: https://github.com/cybercongress/congress/edit/master/knowledge/docs


pages:
    - Home: index.md
    - Contributing: contribute.md
    - cybernode:
        - About node: cybernode/about.md
        - K8s cheat cheet: cybernode/k8s-cheat-sheet.md
        - Dev-setup: cybernode/dev-setup.md
        - Components:
            - Monitoring: cybernode/components/monitoring.md
            - Chains nodes: cybernode/components/chain-nodes.md
            - Requirments: cybernode/components/requirments.md
        - Staging:
            - Setup: cybernode/staging/setup.md
            - Continuous delivery: cybernode/staging/continuous-delivery.md
            - Running application: cybernode/staging/run.md
            - Local sync chains: cybernode/staging/chains.md
            - Kubernetes: cybernode/staging/kubernetes.md
        - Chains:
            - Bitcoin: cybernode/chains/bitcoin.md
            - Ethereum: cybernode/chains/ethereum.md
    - cyber-search:
            - About search: cyberSearch/about-search.md
            - Components:
                - Overview: cyberSearch/components/overview.md
                - Bitcoin: cyberSearch/components/bitcoin.md
                - Ethereum: cyberSearch/components/ethereum.md
            - Contributing:
                - Overview: cyberSearch/contributing/contributing.md
                - Dev-environment: cyberSearch/contributing/dev-environment.md
                - Cheat sheet: cyberSearch/contributing/cheat-sheet.md
    - cyber-markets:
            - About markets: cyberMarkets/about-markets.md
            - Components:
                - Overview: cyberMarkets/components/overview.md
            - Contributing:
                - Dev-enviroment: cyberMarkets/contributing/dev-environment.md
                - Cheat sheet: cyberMarkets/contributing/cheat-sheet.md
                - Contributing: cyberMarkets/contributing/contributing.md
    - cyberjs:
            - Overview: cyberJS/overview.md
            - Development: cyberJS/build.md
    - cyber-browser:
            - About browser: cyberBrowser/Vision_and_Scope.md
            - Staging: cyberBrowser/staging.md
            - Changelog: cyberBrowser/Changelog.md
    - chaingear:
            - About chaingear: Chaingear/overview.md
            - Contracts overwiev: Chaingear/contracts.md
            - Development: Chaingear/development.md
            - Pipelines: Chaingear/pipelines.md
    - cyberd:
            - Overview: cyberd/cyberd.md


# Repository
repo_name: 'congress'
repo_url: 'https://github.com/cybercongress/congress'


# Copyright
copyright: 'Copyright &copy; 2018 cyber•Search'


# Configuration
theme:
  name: null
  custom_dir: 'theme_extend/material'
  font: robo
  favicon: 'img/Logo_cat.svg'
  logo: 'img/Logo_cat.svg'
  language: 'en'
  palette:
    primary: 'green'
  feature:
    tabs: true

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/cybercongress'

extra_css:
  - 'stylesheets/extra.css'
  - https://unpkg.com/mermaid@7.1.0/dist/mermaid.css
  - 'stylesheets/progressbar.css'
extra_javascript:
  - https://unpkg.com/mermaid@7.1.0/dist/mermaid.min.js

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
